### ISSUE TITLE
Option to always regenerate gdnlib

### ISSUE THREAD

**Issue by sargunv** [godot-rust/project-utils#17]
Use case:

I use `cargo build` during development and then `cargo build --release` to prepare for release. If I forget to delete the scripts before switching to release mode, they still refer to the debug build outputs. I'd be less likely to make that mistake if the tool always regenerated the output files. Essentially, I'd like the build script to be the authoritative source of the gdnlib and gdns files, overwriting anything that's already there.

This would overwrite handwritten changes to the files. I'm okay with this (especially as an opt-in option), but if we want to avoid that an alternative approach would be to make the gdnlib refer to outputs in a third directory that doesn't include "debug" or "release" in the path, then modify build scripts to output to that directory. That way, we only need to generate the gdnlib once, and simply swap out the libraries in the third directory as needed.

Looking at the docs, I don't see a way to set the target dir without a build mode, so if the latter route is chosen that's the option that would be needed.

**Comment by sargunv** [comment]
On second thought, I just realized I can just include the following in my build script before generation:

```rust
fs::remove_dir_all("../godot/native").expect("...");
```

So, consider this a feature request for just the latter approach, which would allow keeping targets up to date while maintaining handwritten changes to the resources.

**Comment by Bromeon** [comment]
Closing, as I'm going to archive the repo, which would indefinitely keep this open on your end. I'm thinking of new ways of how to provide utils in the future, also in light of the upcoming [GDExtension binding](https://togithub.com/godot-rust/godot-rust/issues/824).
