### ISSUE TITLE
Always generating code

### ISSUE THREAD

**Issue by halzy** [godot-rust/project-utils#2]
`rerun_if_changed()` is emitting for the generated code and not the source code. 
https://github.com/godot-rust/project-utils/blob/master/src/generate.rs#L190

I believe it should only be emitting for the source files.

**Comment by karroffel** [comment]
That is correct. There was a situation where I removed one of those files by accident and they were not regenerated at the next build.

I think by default build scripts run automatically when the sources change anyway, if I am not mistaken?

**Comment by halzy** [comment]
Ok, the issues appears to be that the generated code is always generated, which changes the timestamps that build.rs uses for checking.
