### ISSUE TITLE
project-utils should not overwrite an existing gdns file and should not create another gdnlib if it is existing

### ISSUE THREAD

**Issue by macalimlim** [godot-rust/project-utils#7]
While trying out the template, I noticed that the project-utils is overwriting the existing `.gdns` file and creating another `.gdnlib` file. It should not overwrite an existing `.gdns` file and create another `.gdnlib` file if another one is already existing.

Essentially if one or both files already exist, don't do anything on that particular file...

**Comment by karroffel** [comment]
Right now the behaviour is that it overrides the file if it's different than the one that would be generated, but it probably makes sense to only write the write at all if it doesn't exist yet. I'll make a patch.
